---
services:
  app:
    image: cosmtrek/air
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: random_episode
      POSTGRES_PASS: Password123!
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: random_episode
    env_file: .env
    volumes:
      - go:/go/src
      - ./:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: Password123!
      POSTGRES_USER: random_episode
      POSTGRES_DB: random_episode
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  go: {}
  pgdata: {}
