name: Deploy from main

on:
  push:
    branches: ['main']

jobs:
  publish-next:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/publish-image.yml
    with:
      tags: |
        type=raw,value=next
